### ISSUE TITLE
SpeechRecognizer#recognize_after_speech yields hypothesis instead of decoder

### ISSUE THREAD

**Issue by chinshr** [watsonbox/pocketsphinx-ruby#17]
Does it make sense to [yield a decoder instead of a hypothesis](https://github.com/watsonbox/pocketsphinx-ruby/blob/master/lib/pocketsphinx/speech_recognizer.rb#L130-L132) in `Pocketsphinx::SpeechRecognizer#recognize_after_speech`?

Essentially, I would like to do this in my code:

```
...
recognizer = Pocketsphinx::AudioFileSpeechRecognizer.new(configuration)
recognizer.recognize(file) do |decoder|
  decoder.hypothesis
  decoder.words
  ...
end
```

**Comment by watsonbox** [comment]
I've made a change so it should now be possible to do:

```ruby
recognizer = Pocketsphinx::AudioFileSpeechRecognizer.new(configuration)
recognizer.recognize(file) do |hypothesis|
  puts hypothesis
  puts recognizer.decoder.words
end
```

You have to use the master branch to test this until I cut a new version.

**Comment by chinshr** [comment]
Yes, that works, thanks.
