### ISSUE TITLE
Using live recorder to generate audio files on silence?

### ISSUE THREAD

**Issue by cjshort** [watsonbox/pocketsphinx-ruby#22]
Hi mate, just came across this library and can't wait to start using it! Just wondering as to whether I could use the live recorder methods to detect when there is no voice and compile the audio into a file such as wav or mp3.

**Comment by watsonbox** [comment]
Not sure this would be possible out of the box, but you should be able to make some changes to use Pocketsphinx's Voice Activity Detection to achieve this.  Perhaps take a look at how [`recognize_after_speech`](https://github.com/watsonbox/pocketsphinx-ruby/blob/master/lib/pocketsphinx/speech_recognizer.rb#L123) works.
